version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.3.0

jobs:
  test:
    docker:
      - image: golang:1.11.10
    steps:
      - checkout
      - run:
          command: go test ./...
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - kubernetes/install
      - run:
          command: |
            mkdir ~/.kube
            cp kube/config.yaml ~/.kube/config
            kubectl config set clusters.bartek.server $CLUSTER_SERVER
            kubectl config set clusters.bartek.certificate-authority-data $CLUSTER_CERT
            kubectl config set users.u-9xsht.token $CLUSTER_TOKEN
            kubectl config set-context $(kubectl config current-context) --namespace=$CLUSTER_NAMESPACE
      - run:
          command: kubectl --record deployment.apps/auto-pocketer-deployment set image deployment.v1.apps/auto-pocketer-deployment auto-pocketer=kruszczynski/auto-pocketer:`echo $CIRCLE_TAG | sed 's/v//'`

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
  ship:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
